export const ORDER_DELIVERED = 4
export const ALL_ORDERS = 1111001111
export const UNASSIGNED_ORDERS = 111101111
export const ORDERS_IN_PRODUCTION = 'OrdersInProdcution'
export const ORDERS_READYFORPICKUP = 'Ready For Pick Up'
export const DELIVERY_TRIPS = 'DeliveryTrips'
export const ORDER_STATUS_DELIVERED = 4
export const ORDER_STATUS_PENDING = 5
export const ORDER_STATUS_CANCELLED = 6
export const ORDER_STATUS_CONFIRMED = 2
export const ORDER_STATUS_READY_FOR_PICKUP = 9
export const ORDER_STATUS_ON_HOLD = 7
export const ORDER_STATUS_ON_HOLD_BY_SALES = 8
export const ORDER_STATUS_SHIPPED = 3
