export const PAYMENT_TYPE_CASH_ON_DELIVERY = 'CASH_ON_DELIVERY'
export const PAYMENT_TYPE_POS = 'POS'
export const PAYMENT_TYPE_MOYASAR_CREDIT_CARD = 'MOYASAR_CREDIT_CARD'
export const PAYMENT_TYPE_MADA_CREDIT_CARD = 'MADA_CREDIT_CARD'
